[package]
name = "solana-elf-from-scratch"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
mollusk-svm = "0.5.1"
solana-instruction = "2.3.0"
solana-pubkey = "2.3.0"
solana-program-error = "2.2.2"
